apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
type: Opaque
data:
  mongo-user: #Use echo -n 'your-username' | base64 to encode and place here
  mongo-password: #Use echo -n 'your-password' | base64 to encode and place here