#Deployment and Service for MongoDB
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-deployment
  labels:
    app: mongo
spec:
  replicas: 1 #how many pods to run
  selector:
    matchLabels: #matches the labels of the pods
      app: mongo
  template: #configuration for the pods
    metadata:
      labels:
        app: mongo
    spec:
      containers:
      - name: mongodb
        image: mongo:5.0
        ports:
        - containerPort: 27017
        env: #Passing secrets as environment variables for MongoDB
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: mongo-user
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: mongo-password 
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-service
spec:
  selector: #selects the pods to route traffic to
    app: mongo #should match the labels of the pods
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 27017 #port on the pod to route traffic to, same as containerPort
